Firestoreのドキュメントをしっかり読んでください

users:
  documentID: userID == auth.uid
  groupCount: Int

  belongingGroups:
    documentID: groupID

groups:
  documentID: auto
  name: String
  userCount: Int
  createdAt: Date

  groupUsers:
    documentID: userID
    id: userID
    name: String
    invitationCode: String?
    createdAt: Date
