Firestoreのドキュメントをしっかり読んでください

users:
  documentID: userID

  name: String?
  iconURL: String?
  createdAt: Date
  updatedAt: Date

  todos:
    documentID: auto

    title: String
    isCompleted: Bool
    completedAt: Date?
    createdAt: Date
    updatedAt: Date


